# Site settings
title: How green is it out there?
email: sean.kearney@usda.gov
url: https://kearney-sp.github.io/grayscale-theme/
baseurl: /grayscale-theme
description: "Use the interactive maps below to see how green the allotments are across the Pawnee National Grasslands.
Maps show satellite-detected the current 'actual' greenness, and greenness relative to historical averages."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
